export const ADD_CONSUMER_TEST_INFO_ARRAY = "ADD_CONSUMER_TEST_INFO_ARRAY";
export const CLEAR_CONSUMER_TEST_INFO_ARRAY = "CLEAR_CONSUMER_TEST_INFO_ARRAY";

export const ADD_PRODUCER_TEST_INFO_ARRAY = "ADD_PRODUCER_TEST_INFO_ARRAY";
export const CLEAR_PRODUCER_TEST_INFO_ARRAY = "CLEAR_PRODUCER_TEST_INFO_ARRAY";
