server:
  port: 8081

spring:
  application:
    name: "consumer-application"
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: identificationDataGroup
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted.packages: "org.message.model"
    topic:
      user-data-topic: "user-data-events-topic"
      report-data-topic: "report-data-events-topic"
      debug-info-data-topic: "debug-info-data-events-topic"
  datasource:
    url: jdbc:mysql://localhost:3306/broker_comparison?encrypt=true&trustServerCertificate=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: HasloDoMySql9925!
  jpa:
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
    open-in-view: false