server:
  port: 8080

spring:
  application:
    name: "producer-application"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      user-data-topic: "user-data-events-topic"
      report-data-topic: "report-data-events-topic"
      debug-info-data-topic: "debug-info-data-events-topic"
  rabbitmq:
    exchange:
      user-name: "user-data-exchange"
      report-name: "report-data-exchange"
      debug-info-name: "debug-info-exchange"